CREATE DATABASE ALMACEN;
USE ALMACEN;

CREATE TABLE ROLES (
	ID_ROL INT(6) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIOS (
	ID_USUARIO INT(6) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(10) NOT NULL,
    ID_ROL INT(6) NOT NULL,
    FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL)
);

CREATE TABLE PRODUCTOS (
	ID_PRODUCTO INT(6) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    CANTIDAD INT(6) DEFAULT 0 NOT NULL,
    ESTATUS VARCHAR(10) DEFAULT 'Activo' NOT NULL
);

CREATE TABLE MOVIMIENTOS (
ID_MOVIMIENTO INT(6) AUTO_INCREMENT PRIMARY KEY,
ID_USUARIO INT(6) NOT NULL,
ID_PRODUCTO INT(6) NOT NULL,
TIPO VARCHAR(10) NOT NULL,
FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

INSERT INTO ROLES (NOMBRE) 
VALUES 
('Administrador'), 
('Almacenista');

INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASENA, ID_ROL)
VALUES
('administrador', 'administrador@empresa.com', 'admin12345', 1),
('almacenista', 'almacenista@empresa.com', 'almacen123', 2);